---
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"

jobs:
  build:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Build Docker Image
        run: docker build -f Dockerfile -t generic-test-runner .

      - name: Run Tests
        run: docker run -w "/opt/test-runner" --entrypoint "bin/run-tests.sh" generic-test-runner
